AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  UploadMenu-Lambda

  Sample SAM Template for UploadMenu-Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8
    MemorySize: 128

Resources:
  UploadMenuFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload_menu/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        UploadMenuApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /upload/{name}
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadMenuApi:
    Description: "API Gateway endpoint URL for Prod stage for UploadMenu function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/{name}"
  UploadMenuFunction:
    Description: "UploadMenu Lambda Function ARN"
    Value: !GetAtt UploadMenuFunction.Arn
  UploadMenuFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UploadMenuFunctionRole.Arn
