AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CreateStripeAccount-Lambda

  Sample SAM Template for CreateStripeAccount-Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 256

Resources:
  CreateStripeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create_stripe_account/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CreateStripe:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateStripeApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Stripe function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create"
  CreateStripeFunction:
    Description: "Create Stripe Lambda Function ARN"
    Value: !GetAtt CreateStripeFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello Create Stripe"
    Value: !GetAtt CreateStripeFunction.Arn
