Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/samshulman/Desktop/personal-projects/QuikSplit-Lambdas/MakePayment-Lambda/make-payment
      Runtime: python3.9
      Architectures:
        - x86_64