Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/samshulman/Desktop/personal-projects/QuikSplit-Lambdas/UploadMenu-Lambda/upload_menu
      Runtime: python3.8
      Architectures:
        - x86_64